rim = {
    &(root_private_key: 0) => tstr .size 16
    &(csk_private_key: 1) => tstr .size 15
    &(revision: 2) => bytes .size 2
    &(oem_data: 3) => bytes .size 16
    &(afm: 4) => afm-body
}


 
measurement-list = [+ measurement-map]
 
measurement-hash = tstr .size 96 / tstr .size 64
 
afm-body = [+ afm-entry-map]

 
data-device-map = {
    &(bus_id: 0) => bytes .size 1
    &(smbus_addr: 1) => bytes .size 1
    &(binding_spec: 2) => bytes .size 1
    &(binding_spec_version: 3) => bytes .size 2
    &(policy: 4) => bytes .size 1
    &(svn: 5) => bytes .size 1
    &(uuid: 6) => bytes .size 16
    &(device_platform_id: 7) => bytes .size 10 / bytes .size 2
    &(device_platform_model: 8) => bytes .size 8 / bytes .size 4
    &(device_platform_version: 9) => bytes .size 2 / bytes .size 4
    &(root_public_key: 10) => tstr .size 11
    &(is_certificate: 11) => tstr .size 1
    &(cert_or_device_pub_key: 12) => [+ tstr .size 28 / tstr .size 32]
    &(measurement: 13) => measurement-list
}
 
device-name = tstr .size 7
 
measurement-map = {
    &(number_of_possible_measurement: 0) => bytes .size 1
    &(meas_value_index: 1) => bytes .size 1
    &(meas_value_type: 2) => bytes .size 1
    &(meas_value_size: 3) => bytes .size 1
    &(measurement: 4) => [+ measurement-hash]
}
 
header-device-map = {
    &(device_addr: 0) => bytes .size 1
    &(device_platform_id: 1) => bytes .size 4
    &(device_platform_model: 2) => bytes .size 8
    &(device_platform_version: 3) => bytes .size 2
}
 
afm-header-map = {
    &(device0: 0) => header-device-map
    &(device1: 1) => header-device-map
    &(device2: 2) => header-device-map
}
 
device-list = [+ device-name]
 

 
afm-data-map = {
    &(data_device0_map: 0) => data-device-map
    &(data_device1_map: 1) => data-device-map
    &(data_device2_map: 2) => data-device-map
}
 
afm-entry-map = {
    &(is_add_on: 0) => 0..1
    &(list_devices: 1) => device-list
    &(list_addon_devices: 2) => device-list
    &(afm_header: 3) => afm-header-map
    &(afm_data: 4) => afm-data-map
}
 
