#!/bin/bash
# This script cleans up the output directories and files generated by the CoDice tests.

rm Attester/Evidence/*

rm Endorser/AFM_Manifest/*
rm Endorser/BMC_PCH_Manifest/*
rm Endorser/Combined_Manifests/*
rm Endorser/Endorsements/*

rm Verifier/Endorsements/*
rm Verifier/Evidence/*

rm Endorser/CoDice_test_endorser
rm Verifier/CoDice_test_verifier
rm Attester/CoDice_test_attester